/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package de.appwerft.j60870;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollFunction;
import org.appcelerator.kroll.KrollProxy;
import org.appcelerator.kroll.annotations.Kroll;
import org.openmuc.j60870.Connection;
import org.openmuc.j60870.InformationObject;

// This proxy can be created by calling J60870.createExample({message: "hello world"})
@Kroll.proxy(creatableInModule = J60870Module.class)
public class InformationObjectProxy extends KrollProxy {
	// Standard Debugging variables
	private static final String LCAT = "J60870";
	private int address;
	private InformationObject[] infoObj;

	// Constructor
	public InformationObjectProxy() {
		super();

	}

	public InformationObject[] getInformationObjects() {
		return infoObj;
	}

	@Override
	public void handleCreationDict(
			@Kroll.argument(optional = true) KrollDict opts) {
		int informationObjectAddress = 0;
		InformationObject[] informationObjects;

		super.handleCreationDict(opts);

		if (opts.containsKeyAndNotNull("address")) {
			address = opts.getInt("address");
		}

	}

}